ChallongeEloSite/ChallongeEloSite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('', include('display.urls')),
    path('admin/', admin.site.urls),
]

ChallongeEloSite/display/urls.py
from django.urls import path

from . import views

urlpatterns = [
    #ex /display/
    path('', views.index, name='index'),
    path('index.html', views.index, name='index'),
    path('rankings.html', views.rankings, name='rankings'),
    path('doubles.html', views.doubles_rankings, name='doubles'),
    path('players.html', views.players_page, name='players_page'),
    path('players/<int:player_id>/', views.player_detail, name='player_detail'),
    path('tournaments.html', views.tournament_page, name='tournaments'),
]

ChallongeEloSite/display/models.py
from django.db import models

class aliases(models.Model):
	name = models.CharField(max_length=255)
	alias = models.CharField(max_length=255, primary_key=True, db_column="alias")

	def __str__(self):
		return self.name + ":" + self.alias

	class Meta:
		db_table="aliases"

class tournaments(models.Model):
	tourney_id = models.AutoField(primary_key=True, db_column="tourney_id")
	date_started = models.DateTimeField()
	name = models.CharField(max_length=255)
	link = models.CharField(max_length=255)

	def __str__(self):
		return self.name + ", occurred at: " + str(self.date_started) + " found online at: " + self.link

	def getDate(self):
		return str(self.date_started)[:10]

	class Meta:
		db_table="tournaments"
		ordering=['date_started']

class players(models.Model):
	player_id = models.AutoField(primary_key=True, db_column="player_id")
	elo = models.IntegerField()
	name = models.CharField(max_length=255, unique=True)

	def __str__(self):
		return "Player " + self.name + " has an elo of " + str(self.elo)

	#return ever opponent this player has ever defeated
	def getWonOpponents(self):
		toReturn = []
		for match in self.won_matches.all():
			if (not(match.loser_id in toReturn)):
				toReturn.append(match.loser_id)

		return toReturn

	#get every opponent ever lost to
	def getLostOpponents(self):
		toReturn = []
		for match in self.lost_matches.all():
			if (not(match.winner_id in toReturn)):
				toReturn.append(match.winner_id)

		return toReturn

	def getOpponents(self):
		beat = self.getWonOpponents()
		lost = self.getLostOpponents()

		toReturn = []

		for id in beat:
			toReturn.append(id)

		for id in lost:
			if (not(id in toReturn)):
				toReturn.append(id)

		toReturn.sort(key=lambda x: x.name)
		return toReturn

	def getMatchesLostTo(self, oppId):
		return self.lost_matches.filter(winner_id=oppId).order_by('tourney_id__date_started')

	def getMatchesWonAgainst(self, oppId):
		return self.won_matches.filter(loser_id=oppId).order_by('tourney_id__date_started')

	class Meta:
		db_table="players"

class matches(models.Model):
	match_id = models.AutoField(primary_key=True, db_column="match_id")
	winner_id = models.ForeignKey(players, on_delete=models.CASCADE, db_column="winner_id", related_name="won_matches")
	loser_id = models.ForeignKey(players, on_delete=models.CASCADE, db_column="loser_id", related_name="lost_matches")
	winner_score = models.IntegerField()
	loser_score = models.IntegerField()
	tourney_id = models.ForeignKey(tournaments, on_delete=models.CASCADE, db_column="tourney_id")

	def __str__(self):
		return str(self.winner_id) + " " + str(self.winner_score) + ":" + str(self.loser_score) + " " + str(self.loser_id) + " at touranment " + str(self.tourney_id)

	class Meta:
		db_table="matches"

class placings(models.Model):
	placing_id = models.AutoField(primary_key=True, db_column="placing_id")
	player_id = models.ForeignKey(players, on_delete=models.CASCADE, db_column="player_id")
	tourney_id = models.ForeignKey(tournaments, on_delete=models.CASCADE, db_column="tourney_id")
	placing = models.IntegerField()

	def __str__(self):
		return str(self.player_id) + " placed " + str(self.placing) + " at " + str(self.tourney_id)

	class Meta:
		db_table="placings"
		ordering=['tourney_id__date_started']

ChallongeEloSite/display/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from datetime import datetime

from . import models
from .models import *

# Create your views here.
def index(request):
	return render(request, 'display/index.html')

def rankings(request):
	#get latest time
	line = tournaments.objects.latest(field_name='date_started').getDate()

	#get only the latest date, not date and time

	return render(request, 'display/rankings.html', {'lastDate': line, 'players': players.objects.exclude(name__icontains=" and ").order_by('-elo')})
def doubles_rankings(request):
	#get latest time
	line = tournaments.objects.latest(field_name='date_started').getDate()

	#get only the latest date, not date and time
	return render(request, 'display/doubles.html', {'lastDate': line, 'players': players.objects.filter(name__contains=" and ").order_by('-elo')})

def players_page(request):
	line = tournaments.objects.latest(field_name='date_started').getDate()

	#get only the latest date, not date and time
	return render(request, 'display/players.html', {'lastDate': line, 'players': players.objects.all().order_by('name')})

def player_detail(request, player_id):
	player = get_object_or_404(players, pk=player_id)
	return render(request, 'display/player_detail.html', {'player': player})

def tournament_page(request):
	#get latest time
	line = tournaments.objects.latest(field_name='date_started').getDate()

	#this should be a table TODO TODO ADD STYLE
	#every table row should have a drop down
	#these drop downs should give the final placings for that tournament

	#get only the latest date, not date and time
	return render(request, 'display/tournaments.html', {'lastDate': line, 'tournaments': tournaments.objects.all().order_by('date_started')})

ChallongeEloSite/display/templates/display/doubles.html
<html>

{% load static %}

<head>
	<title>Powell Smash Rankings</title>
	<link href="{% static 'display/style.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="background"><img alt="" class="stretch" src="{% static 'display/background.png' %}" /></div>

<div class="center"><img width ="100%" height = "35%" alt="logo" src="{% static 'display/logo.png' %}" />
<ul class="top">
	<li><a href="{% url 'index' %}">About Us</a></li>
	<li><a href="{% url 'rankings' %}">Individual Elo</a></li>
	<li><a class="active" href="{% url 'doubles' %}">Team Elo</a></li>
	<li><a href="{% url 'tournaments' %}">Tournaments</a></li>
	<li><a href="{% url 'players_page' %}">Players</a></li>
</ul>

<h2><b>Powell Smash Rankings -- Doubles</b></h2>
<p><b>Click a team's name to see their records.</b></p>
<p><b>Includes all tournament data up to: {{lastDate}}</b></p>
{% for player in players %}
	<p>{{ forloop.counter }}. <a href="{% url 'player_detail' player.player_id %}">{{ player.name }}</a>  |  {{ player.elo }}</p>
{% endfor %}
</div>
</body>
</html>

ChallongeEloSite/display/templates/display/index.html
<html>

{% load static %}

<head>
	<title>Powell Smash Rankings</title>
	<link href="{% static 'display/style.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="background"><img alt="" class="stretch" src="{% static 'display/background.png' %}" /></div>

<div class="center"><img width ="100%" height = "35%" alt="logo" src="{% static 'display/logo.png' %}" />
<ul class="top">
	<li><a class="active" href="{% url 'index' %}">About Us</a></li>
	<li><a href="{% url 'rankings' %}">Individual Elo</a></li>
	<li><a href="{% url 'doubles' %}">Team Elo</a></li>
	<li><a href="{% url 'tournaments' %}">Tournaments</a></li>
	<li><a href="{% url 'players_page' %}">Players</a></li>
</ul>

<h2>Powell Smash</h2>

<p class="pcenter">Powell Smash is a local organization of SSBM players north of Columbus in Central Ohio.</p>

<p class="pcenter">We run free-to-enter tournaments pretty much every weekend at someone&#39;s house, and attend public tournaments, as well as hosting two to three major, public tournaments with a buy-in a year. We are looking to grow, and if you are nearby Powell or Lewis Center, Ohio, send an email to powellsmash@gmail.com to get involved!</p>

<!--
<p class="pcenter">Some of our history can be found in this <a href="blogpost-historypart1.html">blog post.</a></p>
-->
<p class="pcenter">This page is mostly for those players already involved, but if you have an interest in joining us and were given the link by one of our players, welcome! Take a look around and see if you&#39;d want to join us!</p>

<p class="pcenter">Some of our most notable acheievements include one of our players making it out of pools at Shuffle VII, one of our players making fifth in his pool at Genesis 3, one of our players getting 104% on M2K in PM, and three players making it out of pools at Screw It Just Upsmash!</p>

<p class="pcenter">One of main features of this site are our Power Rankings, check those out with the rankings tab above!</p>

<p class="pcenter">More is coming to this site soon, keep your eyes open!</p>

<p>&nbsp;</p>

<p class="pcenter"><img alt="Nicky V M2K" height="350" src="{% static 'display/m2k.jpg' %}" style="float:left" width="250" /> <img alt="Nicky V M2K" height="350" src="{% static 'display/sijs.jpg' %}" style="float:right" width="250" /></p>

<p class="pcenter">To the left is Nicky S, one of our top players, playing Mew2King at Shuffle VII.</p>

<p class="pcenter">To the right are some of our players at ESI&#39;s Screw it Just Shine, playing against <a href="https://twitter.com/R2_SSBM">R2</a>.</p>

<p class="pcenter">Top left: Ali S. Top right: Caleb F. Bottom left: Tony G. Playing: Nicky S.</p>

<p class="pcenter">In both cases, the tournament took place at Ohio State&#39;s Union building, and the picture was taken by Joe F. Shoutouts to ESI for putting on great tournaments!</p>

<p class="pcenter">Follow us on <a href="https://twitter.com/PowellSmash">Twitter</a>!</p>

<p class="pcenter">Check our old brackets out on <a href="http://challonge.com/users/powellsmash">Challonge</a>!</p>

<p class="pcenter">Check out our VODs and other content on <a href="https://www.youtube.com/channel/UCdNBX7zWJXSkFEfPMhZ9bsQ">YouTube!</a></p>

<p class="pcenter">Keep an eye out for a subreddit, coming soon!</p>
</div>
</body>
</html>

ChallongeEloSite/display/templates/display/player_detail.html
<html>

{% load static %}
{% load main_tags %}

<head>
	<title>Powell Smash Rankings</title>
	<link href="{% static 'display/style.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="background"><img alt="" class="stretch" src="{% static 'display/background.png' %}" /></div>

<div class="center"><img width ="100%" height = "35%" alt="logo" src="{% static 'display/logo.png' %}" />
<ul class="top">
	<li><a href="{% url 'index' %}">About Us</a></li>
	<li><a href="{% url 'rankings' %}">Individual Elo</a></li>
	<li><a href="{% url 'doubles' %}">Team Elo</a></li>
	<li><a href="{% url 'tournaments' %}">Tournaments</a></li>
	<li><a href="{% url 'players_page' %}">Players</a></li>
</ul>

<h2>Stats and Ranking for {{ player.name }}</h2>
{{ player.name }}, Current Elo: {{ player.elo }}
<p></p>
<table border = "1">
<tr>
<th>Date</th>
<th>Name</th>
<th>Finished</th>
</tr>
{% for curr_placing in player.placings_set.all %}
<tr>
<td>{{ curr_placing.tourney_id.getDate }}</td>
<td><a href = "{{ curr_placing.tourney_id.link }}">{{ curr_placing.tourney_id.name }}</a></td>
<td>{{ curr_placing.placing }}</td>
</tr>
{% endfor %}
</table>

{% for oppId in player.getOpponents %}
<!-- loading matches -->
{% getMatchesWonAgainstTag player oppId.player_id as matchesWon %}
{% getMatchesLostAgainstTag player oppId.player_id as matchesLost %}

{% getSetAndGameCount matchesWon matchesLost as results %}

<p><b>Against <a href = "{% url 'player_detail' oppId.player_id %}">{{ oppId.name }}</a>:</b></p>
{% for match in matchesWon %}
<p>{{ player.name }} {{ match.winner_score }}-{{ match.loser_score }} {{ match.loser_id.name }} at {{ match.tourney_id.name }}</p>
{% endfor %}
{% for match in matchesLost %}
<p>{{ match.winner_id.name }} {{ match.winner_score }}-{{ match.loser_score }} {{ player.name }} at {{ match.tourney_id.name }}</p>
{% endfor %}
<p>Total Record in Games: {{ results.0 }}</p>
<p>Total Record in Sets: {{ results.1 }}</p>

<p> </p>
{% endfor %}
</div>
</body>
</html>

ChallongeEloSite/display/templates/display/players.html
<html>

{% load static %}

<head>
	<title>Powell Smash Rankings</title>
	<link href="{% static 'display/style.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="background"><img alt="" class="stretch" src="{% static 'display/background.png' %}" /></div>

<div class="center"><img width ="100%" height = "35%" alt="logo" src="{% static 'display/logo.png' %}" />
	<ul class="top">
		<li><a href="{% url 'index' %}">About Us</a></li>
		<li><a href="{% url 'rankings' %}">Individual Elo</a></li>
		<li><a href="{% url 'doubles' %}">Team Elo</a></li>
		<li><a href="{% url 'tournaments' %}">Tournaments</a></li>
		<li><a class="active" href="{% url 'players_page' %}">Players</a></li>
	</ul>

<h2><b>Powell Smash Rankings</b></h2>
<p><b>Click a player's name to see their records.</b></p>
<p><b>Includes all tournament data up to: {{lastDate}}</b></p>
{% for player in players %}
	<p>{{ forloop.counter }}. <a href="{% url 'player_detail' player.player_id %}">{{ player.name }}</a>  |  {{ player.elo }}</p>
{% endfor %}
</div>
</body>
</html>

ChallongeEloSite/display/templates/display/rankings.html
<html>

{% load static %}

<head>
	<title>Powell Smash Rankings</title>
	<link href="{% static 'display/style.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="background"><img alt="" class="stretch" src="{% static 'display/background.png' %}" /></div>

<div class="center"><img width ="100%" height = "35%" alt="logo" src="{% static 'display/logo.png' %}" />
<ul class="top">
	<li><a href="{% url 'index' %}">About Us</a></li>
	<li><a class="active" href="{% url 'rankings' %}">Individual Elo</a></li>
	<li><a href="{% url 'doubles' %}">Team Elo</a></li>
	<li><a href="{% url 'tournaments' %}">Tournaments</a></li>
	<li><a href="{% url 'players_page' %}">Players</a></li>
</ul>

<h2><b>Powell Smash Rankings</b></h2>
<p><b>Click a player's name to see their records.</b></p>
<p><b>Includes all tournament data up to: {{lastDate}}</b></p>
{% for player in players %}
	<p>{{ forloop.counter }}. <a href="{% url 'player_detail' player.player_id %}">{{ player.name }}</a>  |  {{ player.elo }}</p>
{% endfor %}
</div>
</body>
</html>

ChallongeEloSite/display/templates/display/tournaments.html
<html>

{% load static %}

<head>
	<title>Powell Smash Rankings</title>
	<link href="{% static 'display/style.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="background"><img alt="" class="stretch" src="{% static 'display/background.png' %}" /></div>

<div class="center"><img width ="100%" height = "35%" alt="logo" src="{% static 'display/logo.png' %}" />
	<ul class="top">
		<li><a href="{% url 'index' %}">About Us</a></li>
		<li><a href="{% url 'rankings' %}">Individual Elo</a></li>
		<li><a href="{% url 'doubles' %}">Team Elo</a></li>
		<li><a class="active" href="{% url 'tournaments' %}">Tournaments</a></li>
		<li><a href="{% url 'players_page' %}">Players</a></li>
	</ul>

<h2><b>Powell Smash Rankings</b></h2>
<p><b>Click a player's name to see their records.</b></p>
<p><b>Includes all tournament data up to: {{lastDate}}</b></p>
<table border = "1">
	<tr>
		<th>Date</th>
		<th>Name</th>
	</tr>
{% for tournament in tournaments %}
	<tr>
		<td>{{ tournament.getDate }}</td>
		<td><a href="{{ tournament.link }}">{{ tournament.name }}</a></td>
	</tr>
{% endfor %}
</div>
</body>
</html>